import CompletedGatheringHeader from "@/components/organisms/header/CreateReviewHeader";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "모임 리뷰",
  description: "Generated by create next app",
};

export default function ReviewCreateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full flex-col">
      <CompletedGatheringHeader />
      {children}
    </div>
  );
}
