import Header from "@/components/organisms/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "알림 전체 화면",
  description: "Generated by create next app",
};

export default function NotificationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-full flex-col">
      <Header title="알림" backButton />
      {children}
    </div>
  );
}
